source "https://rubygems.org"

gem "rails", "~> 8.0.0.beta1"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem "propshaft"
gem "solid_queue"
gem 'solid_queue_dashboard', path: '..'
gem "thruster", require: false
gem "ostruct"
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
end
